name: e2e-testing
run-name: Create all entities in Seqera Platform from end-to-end with seqerakit
# This workflow can be triggered manually with GitHub actions workflow dispatch button.
# It will automate the end-to-end creation all of the following entities in Seqera Platform.

on:
  workflow_dispatch:

jobs:
  e2e-testing:
    name:
    if: github.repository == 'seqeralabs/seqera-kit'
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {0}
    env:
      TOWER_ACCESS_TOKEN: ${{ secrets.TOWER_ACCESS_TOKEN }}
      TOWER_GITHUB_PASSWORD: ${{ secrets.TOWER_GITHUB_PASSWORD }}
      DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_ASSUME_ROLE_ARN: ${{ secrets.AWS_ASSUME_ROLE_ARN }}
      AZURE_BATCH_KEY: ${{ secrets.AZURE_BATCH_KEY }}
      AZURE_STORAGE_KEY: ${{ secrets.AZURE_STORAGE_KEY }}
      GOOGLE_KEY: ${{ secrets.GOOGLE_KEY }}
      SENTIEON_LICENSE_BASE64: ${{ secrets.SENTIEON_LICENSE_BASE64 }}
    steps:
      - name: Check out source-code repository
        uses: actions/checkout@v3

      - name: Setup conda
        uses: conda-incubator/setup-miniconda@v2.2.0
        with:
          miniconda-version: 'latest'
          channels: bioconda, conda-forge, defaults
          use-only-tar-bz2: true # IMPORTANT: This needs to be set for caching to work properly!
          auto-update-conda: true
          auto-activate-base: true
          python-version: '3.10'
      - name: Install seqerakit
        run: |
          conda create -y --name seqerakit seqerakit
          conda activate seqerakit || true
      - name: Create all entities on Seqera Platform from end-to-end
        run: |
          temp_file=$(mktemp -q)
          echo $GOOGLE_KEY | base64 -d > $temp_file
          export GOOGLE_KEY=$temp_file

          seqerakit examples/yaml/seqerakit-e2e.yml

      - name: Cleanup entities on Seqera Platform
        run: |
          seqerakit examples/yaml/seqerakit-e2e.yml --delete
